USE [master]
GO

/****** Object:  Database [CBIndividualProject]    Script Date: 11/19/2018 12:23:55 AM ******/
CREATE DATABASE [CBIndividualProject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CBIndividualProject', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CBIndividualProject.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CBIndividualProject_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CBIndividualProject_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CBIndividualProject] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CBIndividualProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CBIndividualProject] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CBIndividualProject] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CBIndividualProject] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CBIndividualProject] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CBIndividualProject] SET ARITHABORT OFF 
GO

ALTER DATABASE [CBIndividualProject] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CBIndividualProject] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CBIndividualProject] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CBIndividualProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CBIndividualProject] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CBIndividualProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CBIndividualProject] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CBIndividualProject] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CBIndividualProject] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CBIndividualProject] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CBIndividualProject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CBIndividualProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CBIndividualProject] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CBIndividualProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CBIndividualProject] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CBIndividualProject] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CBIndividualProject] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CBIndividualProject] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CBIndividualProject] SET  MULTI_USER 
GO

ALTER DATABASE [CBIndividualProject] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CBIndividualProject] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CBIndividualProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CBIndividualProject] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CBIndividualProject] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CBIndividualProject] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CBIndividualProject] SET  READ_WRITE 
GO

